server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8096

spring:
  datasource:
    hikari: # 초당 30tps 트랜잭션 설정
      maximum-pool-size: 30
  jpa:
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true